version: "3.9"
    
services:

  message_broker:
    image: message_broker:v1
    container_name: message_broker
    ports: 
      - "4444:4444"
    networks:
      - mbnet

  consumer:
    image: consumer:v1
    container_name: consumer
    ports:
      - "4446:4446"
    networks:
      - mbnet
    depends_on:
      - message_broker

  producer:
    image: producer:v1
    container_name: producer
    ports: 
      - "4445:4445"
    networks:
      - mbnet
    depends_on:
      - consumer


networks:
  mbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
