version: "3.9"
    
services:

  message_broker:
    image: broker:v1
    container_name: br
    ports: 
      - "4444:4444"
    networks:
      - mbnet
  
  a_producer:
    image: producer:v1
    container_name: pr
    ports: 
      - "4445:4445"
    networks:
      - mbnet
  
  a_consumer:
    image: consumer:v1
    container_name: co
    ports: 
      - "4446:4446"
    networks:
      - mbnet

networks:
  mbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
